### ISSUE TITLE
Doesn't install on Python 2.7.10

### ISSUE THREAD

**Issue by c4s4** [PyAr/fades#117]
When installing on Python 2.7.10, I have following trace:

Collecting fades
  Using cached fades-3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python2.7/site-packages (from fades)
Building wheels for collected packages: fades
  Running setup.py bdist_wheel for fades
  Complete output from command /home/casa/dsk/env/bin/python -c "import setuptools;__file__='/tmp/pip-build-mR6WSi/fades/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpcTJyMEpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fades
  copying fades/parsing.py -> build/lib/fades
  copying fades/pipmanager.py -> build/lib/fades
  copying fades/pkgnamesdb.py -> build/lib/fades
  copying fades/__init__.py -> build/lib/fades
  copying fades/helpers.py -> build/lib/fades
  copying fades/envbuilder.py -> build/lib/fades
  copying fades/cache.py -> build/lib/fades
  copying fades/main.py -> build/lib/fades
  copying fades/logger.py -> build/lib/fades
  running build_scripts
  creating build/scripts-2.7
  copying and adjusting bin/fades -> build/scripts-2.7
  changing mode of build/scripts-2.7/fades from 644 to 755
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/home
  creating build/bdist.linux-x86_64/wheel/home/casa
  creating build/bdist.linux-x86_64/wheel/home/casa/dsk
  creating build/bdist.linux-x86_64/wheel/home/casa/dsk/env
  creating build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share
  creating build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades
  creating build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  copying build/lib/fades/parsing.py -> build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  copying build/lib/fades/pipmanager.py -> build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  copying build/lib/fades/pkgnamesdb.py -> build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  copying build/lib/fades/__init__.py -> build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  copying build/lib/fades/helpers.py -> build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  copying build/lib/fades/envbuilder.py -> build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  copying build/lib/fades/cache.py -> build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  copying build/lib/fades/main.py -> build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  copying build/lib/fades/logger.py -> build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades
  running install_egg_info
  running egg_info
  writing requirements to fades.egg-info/requires.txt
  writing fades.egg-info/PKG-INFO
  writing top-level names to fades.egg-info/top_level.txt
  writing dependency_links to fades.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'fades.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'fades.egg-info/SOURCES.txt'
  Copying fades.egg-info to build/bdist.linux-x86_64/wheel/home/casa/dsk/env/share/fades/fades-3-py2.7.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/fades-3.data
  creating build/bdist.linux-x86_64/wheel/fades-3.data/scripts
  copying build/scripts-2.7/fades -> build/bdist.linux-x86_64/wheel/fades-3.data/scripts
  changing mode of build/bdist.linux-x86_64/wheel/fades-3.data/scripts/fades to 755
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-mR6WSi/fades/setup.py", line 109, in <module>
      'virtualenv': 'virtualenv',
    File "/opt/python/2.7.10/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/opt/python/2.7.10/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/opt/python/2.7.10/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/casa/dsk/env/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 211, in run
      self.run_command('install')
    File "/opt/python/2.7.10/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/opt/python/2.7.10/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-mR6WSi/fades/setup.py", line 47, in run
      with open(script_path, 'rt', encoding='utf8') as fh:
  TypeError: 'encoding' is an invalid keyword argument for this function
  
  ----------------------------------------
Failed to build fades
Installing collected packages: fades
  Running setup.py install for fades
    Complete output from command /home/casa/dsk/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-mR6WSi/fades/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-trKAv0-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/casa/dsk/env/include/site/python2.7/fades:
    running install
    running build
    running build_py
    running build_scripts
    running install_lib
    copying build/lib/fades/parsing.py -> /home/casa/dsk/env/share/fades/fades
    copying build/lib/fades/pipmanager.py -> /home/casa/dsk/env/share/fades/fades
    copying build/lib/fades/pkgnamesdb.py -> /home/casa/dsk/env/share/fades/fades
    copying build/lib/fades/__init__.py -> /home/casa/dsk/env/share/fades/fades
    copying build/lib/fades/helpers.py -> /home/casa/dsk/env/share/fades/fades
    copying build/lib/fades/envbuilder.py -> /home/casa/dsk/env/share/fades/fades
    copying build/lib/fades/cache.py -> /home/casa/dsk/env/share/fades/fades
    copying build/lib/fades/main.py -> /home/casa/dsk/env/share/fades/fades
    copying build/lib/fades/logger.py -> /home/casa/dsk/env/share/fades/fades
    byte-compiling /home/casa/dsk/env/share/fades/fades/parsing.py to parsing.pyc
    byte-compiling /home/casa/dsk/env/share/fades/fades/pipmanager.py to pipmanager.pyc
    byte-compiling /home/casa/dsk/env/share/fades/fades/pkgnamesdb.py to pkgnamesdb.pyc
    byte-compiling /home/casa/dsk/env/share/fades/fades/__init__.py to __init__.pyc
    byte-compiling /home/casa/dsk/env/share/fades/fades/helpers.py to helpers.pyc
    byte-compiling /home/casa/dsk/env/share/fades/fades/envbuilder.py to envbuilder.pyc
    byte-compiling /home/casa/dsk/env/share/fades/fades/cache.py to cache.pyc
    byte-compiling /home/casa/dsk/env/share/fades/fades/main.py to main.pyc
    byte-compiling /home/casa/dsk/env/share/fades/fades/logger.py to logger.pyc
    running install_egg_info
    running egg_info
    writing requirements to fades.egg-info/requires.txt
    writing fades.egg-info/PKG-INFO
    writing top-level names to fades.egg-info/top_level.txt
    writing dependency_links to fades.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'fades.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'fades.egg-info/SOURCES.txt'
    removing '/home/casa/dsk/env/share/fades/fades-3-py2.7.egg-info' (and everything under it)
    Copying fades.egg-info to /home/casa/dsk/env/share/fades/fades-3-py2.7.egg-info
    running install_scripts
    copying build/scripts-2.7/fades -> /home/casa/dsk/env/bin
    changing mode of /home/casa/dsk/env/bin/fades to 755
    writing list of installed files to '/tmp/pip-trKAv0-record/install-record.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mR6WSi/fades/setup.py", line 109, in <module>
        'virtualenv': 'virtualenv',
      File "/opt/python/2.7.10/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/python/2.7.10/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/python/2.7.10/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-mR6WSi/fades/setup.py", line 47, in run
        with open(script_path, 'rt', encoding='utf8') as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------

**Comment by facundobatista** [comment]
"fades" is a "Python 3 only" package. 

You need Python 3 to install and use fades.

Note however, that with fades you can still make virtualenvs with python 2 inside (use --python option).

Thanks for your time and interest! Regards,
