### ISSUE TITLE
Detect new versions of currently installed dependencies

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#118]
The idea is to upgrade packages and inform of new versions.

So, for example, user has a requirements.txt with the following:

    requests
    zaraza==1.8

So, the moment the user runs fades -d requirements.txt it installs requests 1 (that is what is in pypi and zaraza 1.8, and opens the interpreter.
 
One day, in pypi these two packages get updated: requests 2 and zaraza 1.9.

If the user does

    fades -d requirements.txt --check-updates
    
it will just log in INFO that there is a new zaraza (1.9), but it doesn't really use it. However, as requests didn't specify a version, and it knows there's an updated version, it will use it. So it will create a new venv with requests 2 y zaraza 1.8.

**Comment by humitos** [comment]
How I can do this right now?

I've used "subliminal" for some time (version 1.0.1). Today I noticed there is a new version: 1.1.1 and I want my "fadesenv" to upgraded. So, how I can do this manually? I mean, remove the fadesenv so fades won't find a matching env and it will create a new-update-env for this version.

**Comment by gilgamezh** [comment]
@humitos you have to specify the versión. `subliminal==1.1.1`
