### ISSUE TITLE
support install from local path

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/fades#130]
Example:

`fades -d ~/gilgamezh/code/awesome_lib/`

check --> http://pip.readthedocs.org/en/stable/reference/pip_install/#requirements-file-format

**Comment by gilgamezh** [comment]
We should also support "editable install". 
http://pip.readthedocs.org/en/stable/reference/pip_install/#editable-installs

**Comment by facundobatista** [comment]
Regarding the local path... can't we support ```file://~/gilgamezh/code/awesome_lib/``` the same way we'll support ```pip://etc```?

Regarding editable install, can't that be an option you pass to pip? do we need to do something beyond that?

**Comment by gilgamezh** [comment]
>Regarding the local path... can't we support file://~/gilgamezh/code/awesome_lib/ the same way we'll >support pip://etc?

I have te check how much work we can delegate to pip yo answer it ;)

The problem with the `editable` is that we have to pass this option only for a specific dependency. The pip options are for all the dependencies....

**Comment by facundobatista** [comment]
In any case (delegating it easily to pip or having to do more work), I think we could provide this

**Comment by gilgamezh** [comment]
currently working 

```# Use a library from a local branch

$ fades -d file:///home/facundo/devel/reps/tritcask/
>>> import tritcask
>>> tritcask.__file__
'/home/facundo/.local/share/fades/86bbf1df-f9a8-459f-adc5-33b2a4f715da/lib/python3.5/site-packages/tritcask/__init__.py'
```
