### ISSUE TITLE
Create a "terminal video" about using fades

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#144]
Can be something like it's done here:

  https://github.com/mptre/yank

but I'd prefer a voice in off telling what's going on.

The video should take ~2, 3 minutes.

Also, we could make several small ones, muted, can be even gifs, like "how to use a requirement.txt file", or "how to start a specific django project"... I wouldn't do a gif for _every_ feature, but, say, the top 5....

**Comment by gilgamezh** [comment]
Full video released (https://www.youtube.com/watch?v=BCTd_TyCm98). We have yo create some short gif with samples

**Comment by facundobatista** [comment]
@gilgamezh I'd love feedback on this examples: http://linkode.org/#kZYWYIP4mr43Nc2YIoiJp6
