### ISSUE TITLE
How I should install it?

### ISSUE THREAD

**Issue by humitos** [PyAr/fades#16]
I didn't find any docs to install `fades` :(

I tried to install it by pip:
```
pip install git+https://github.com/PyAr/fades.git
```

but it didn't work.

Log here: http://linkode.org/tYdaktygyiBtYTR9mHhRP6

**Comment by facundobatista** [comment]
Proper instructions added to the readme :)

**Comment by gilgamezh** [comment]
installing with pip using the repo URL is also working now :smile: 

check #27
