### ISSUE TITLE
Arguments with long text

### ISSUE THREAD

**Issue by humitos** [PyAr/fades#161]
Not sure if I should report this here, but it's only happening when I use fades.

I'm using `docopt` to create a CLI and it's working without problem. Here is an example of what I want to do:
```python
# -*- coding: utf-8 -*-

"""Echo --text argument

Usage:
  echo.py (-t=TEXT | --text=TEXT)
  echo.py --help
  echo.py --version

Options:
  -t, --text TEXT            Text to be echoed
"""

from docopt import docopt  # fades


if __name__ == '__main__':
    arguments = docopt(__doc__, version='Echo 0.1')

    print(arguments['--text'])

```

This is totally working script and I'm calling it like this:
```
$ python echo.py --t hola
hola
$ python echo.py --text="hola chavo"
hola chavo
$
```

Then, I call it using fades and there is an issue with the "argument with many words":
```
$ fades -p python3 echo.py -t hola
hola
$ fades -p python3 echo.py --text="hola chavo"
Usage:
  echo.py (-t=TEXT | --text=TEXT)
  echo.py --help
  echo.py --version
$
```

Do you know what's the problem here?

**Comment by facundobatista** [comment]
It's working here:

    $ fades -v th1.py --text="hola chavo"
    ... (debug lines) ...
    hola chavo

See full debug lines in http://linkode.org/b5WVolF7lySg6bXTSu6iC

Would you mind to call your NON working example with -v and gives us the debug lines? Thanks!

**Comment by humitos** [comment]
Full debug lines: http://linkode.org/UyBEEApQjz3HBnnsxNEmV1

```
$ fades -v -p python3 echo.py --text='hola chavo'
```

**Comment by facundobatista** [comment]
From my linkode:

    Arguments: Namespace(child_options=['--text=hola chavo'], ...

From your linkode:

    Arguments: Namespace(check_updates=False, child_options=['--text=hola', 'chavo'] ...

Could you please call your non working example and give us the debug lines, again, but this time including in the linkode the line where you're executing fades? Thanks!

**Comment by humitos** [comment]
Here is the full log: http://linkode.org/VlneQkynxLaX5ImqQODLO3

I found the issue. Check this out:
```
[10:53] humitos: tools> which fades
/home/humitos/bin/fades
[10:53] humitos: tools> cat /home/humitos/bin/fades
#!/bin/bash

FADES_BIN=/home/humitos/.virtualenvs/fades/bin/fades
$FADES_BIN $*
[10:54] humitos: tools> 
```

Using the full path without the `~/bin/fades` bash script works properly:
```
[10:54] humitos: tools> /home/humitos/.virtualenvs/fades/bin/fades -v -p python3 echo.py --text='hola chavo'
(debug lines)
hola chavo
```

(maybe this is something else you will want to know when reporting issues)

**Comment by StyXman** [comment]
@humitos: you could have used `bash -x`:

`bash -x /home/humitos/bin/fades ...`

**Comment by humitos** [comment]
@StyXman well, I think it's better to have an aliases like this one:
  alias fades=/home/humitos/.virtualenvs/fades/bin/fades
