### ISSUE TITLE
Named virtual envs

### ISSUE THREAD

**Issue by humitos** [PyAr/fades#164]
This is a feature request and an idea to start talking about this topic.

The idea is to have named virtualenvs instead of using a UUID. Having this feature is all that I need to migrate from virtualenvwrapper (without maintenance anymore: https://doughellmann.com/blog/2016/01/03/virtualenvwrapper-needs-a-new-maintainer/) to fades.

I would like to have a parameter like `-n` (`--venv-name`) to use or create (if it doesn't exist) a particular virtualenv. This is useful when you have a project and you don't want to include in every command the `requirements.txt` file or the `-x` to execute fades plus the command itself.

I'm thinking in something like `fades -n blog -d nikola`. This will create the venv called blog and will install nikola and will activate it. Then we can just run `nikola` without using fades (because we already are inside the venv).

Running a venv in this way will complicate fades to know what packages has each of the named venv installed on it, because after running `fades activate blog` I could do `pip install somenewpackage` and fades won't know about that.

Another commands could be `fades deactivate` (alias to `deactivate`) and `fades activate blog`.

What do you think?

**Comment by gilgamezh** [comment]
I think ifades as a virtualenvs cache. So named virtualenvs are not the best idea for me.

Doesn't have to remember the virtualenv name is a feature! (check our LT)

I'm using it:
```
 ~  alias | grep nikola
nikola='fades -d nikola -x nikola'
```
or for my django projects I'm using `manage='fades -r requirements.txt manage.py'`. As a side effect I never forget to add a dependency to my requeriments.txt file ;)

I'm losing any use case?

**Comment by facundobatista** [comment]
This is the opposite intended behaviour for fades.

The idea for fades is that you shouldn't need to care about any particular virtualenv, and that you don't "enter" or "exit" from them (which is something that fades doesn't even attempt to do, and will unleash a lot of difficulties regarding multiplatform).

You say to create a venv using fades named X, and then use fades to activate and deactivate... this is close enough to native virtualenv behaviour that you probably could use it directly.

So, we'll not be doing this.

**Comment by humitos** [comment]
@facundobatista @gilgamezh thank for your comments. I will try the @gilgamezh solution
