### ISSUE TITLE
Package names

### ISSUE THREAD

**Issue by humitos** [PyAr/fades#17]
How does *fades* the name of the package that it should install?

I think it's taking the name from the `import` line but sometimes this is not correct: for example: beautifulsoup.

I have this in my `.py` file:
```
from bs4 import BeautifulSoup  # fades.pypi
```

and *fades* tries to install the package named `bs4` which is incorrect because the proper name is: `beautifulsoup4`

I suggest to use something like this:
```
from bs4 import BeautifulSoup  # fades.pypi beautifulsoup4
```

**Comment by humitos** [comment]
Following the fades' philosophy (?), I think there should be a list of "known package names" where it says:

```
bs4: beautifulsoup4
```

and so on...

**Comment by facundobatista** [comment]
Moved the "database of name conversion" to issue #32
