### ISSUE TITLE
 Continous Integration on Windows

### ISSUE THREAD

**Issue by matibarriento** [PyAr/fades#198]
I found this tool for  **Continous Integration on Windows** 
DOCS
https://www.appveyor.com/docs
https://www.appveyor.com/docs/build-configuration

DEMO
https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

I hope you find this useful

**Comment by facundobatista** [comment]
Thanks! Using it.

**Comment by facundobatista** [comment]
I created #271 for this (but will keep this open until appveyor goes green)

**Comment by matibarriento** [comment]
There is a badge (like travis, coveralls) to see the progress/error?
