### ISSUE TITLE
Using fades without user knowing about it

### ISSUE THREAD

**Issue by sils1297** [PyAr/fades#217]
Hi,

just listening to a lightning talk about fades at europython; we actually have thought about the same problem for coala (coala-analyzer.org): we ideally would love to distribute coala in a way that the user can simply pip install it but automatically uses a virtualenv. I.e. user workflow:

```
pip install coala  # Possibly a slightly other command but no second one.
coala ...
```

For that we'd have to have fades create a venv with the requirements from our requirements.txt upon pip installation and create some kind of fades entrypoint I guess.

Is something like this possible? It's very important to us that the user can actually use fades without knowing it, is able to do it traditionally if he wants it but still has a coala venv and doesn't need root priviliges for installation.

**Comment by facundobatista** [comment]
Absolutely, you could include a script that executes your project under fades, kind of `fades -r requirements.txt bin/whatever`.

As an example, you can see the `test` script from fades itself, that is run under fades ;) (this way, you just clone the project and can run the project no wondering about dependencies): 

```
    https://github.com/PyAr/fades/blob/master/test
```

Of course, the user would need to have fades installed, which it can do with "sudo apt-get install fades" or whatever in the user's operating system.

**Comment by sils1297** [comment]
we'd love to have the virtualenv to be created upon pip installation and also be removed again cleanly in the end.

Looking at this later - maybe we can meet for this?

**Comment by facundobatista** [comment]
Let's meet and talk, yes! I'll be around after the LTs

**Comment by sils1297** [comment]
sitting at the intel stand right now before A1, can you come by?

**Comment by sils1297** [comment]
CC  @mtomwing btw.

**Comment by mtomwing** [comment]
This is really cool. Thanks for the CC!

Want to chat about this tomorrow? I should have time after my talk.

**Comment by sils1297** [comment]
are you at europython as well, Michael? Could we all possibly meet at the
code analysis helpdesk tomorrow afternoon after lunch or so?

**Comment by facundobatista** [comment]
I'll carry my lunch to the help desk area and stay there until 14hs (after lunch there's a talk I want to attend).

BTW, closing this issue (we can keep coordinating a meeting here, or maybe better through the Europython telegram channel)

**Comment by sils1297** [comment]
cool, see you

**Comment by sils1297** [comment]
alright, we're sitting there now, the people with the coala shirts

**Comment by facundobatista** [comment]
Been there a while, then had to run to the bank :(. Please contact me through Telegram (I'm @facundobatista there), thanks!
