### ISSUE TITLE
get-pip.py will  install pip in an outher virtualenv, but not the one fades created

### ISSUE THREAD

**Issue by blueyed** [PyAr/fades#219]
I have created a temporary virtualenv, and `pip install -e`ed fades into it.

When running `fades`, it fails to install pip correctly:
```
% fades -d requests -v
*** fades ***  2016-07-20 15:34:16,759  fades              DEBUG    Running Python sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0) on 'linux'
*** fades ***  2016-07-20 15:34:16,759  fades              DEBUG    Starting fades v. 5.0
*** fades ***  2016-07-20 15:34:16,760  fades              DEBUG    Arguments: Namespace(check_updates=True, child_options=[], child_program=None, clean_unused_venvs=None, dependency=['requests'], executable=False, ipython=True, pip_options=[], python=None, quiet=False, remove=None, requirement=None, system_site_packages=False, verbose=True, version=False, virtualenv_options=[])
*** fades ***  2016-07-20 15:34:16,760  fades.cache        DEBUG    Using cache index: '/home/user/.local/share/fades/venvs.idx'
*** fades ***  2016-07-20 15:34:16,760  fades              DEBUG    Adding ipython dependency because --ipython was detected
*** fades ***  2016-07-20 15:34:16,761  fades              DEBUG    Dependencies from source file: {}
*** fades ***  2016-07-20 15:34:16,761  fades              DEBUG    Dependencies from docstrings: {}
*** fades ***  2016-07-20 15:34:16,761  fades              DEBUG    Dependencies from requirements file: {}
*** fades ***  2016-07-20 15:34:16,761  fades              DEBUG    Dependencies from parameters: {'pypi': [Requirement.parse('requests')]}
*** fades ***  2016-07-20 15:34:16,998  fades.helpers      INFO     There is a new version of ipython: 5.0.0 and will use it.
*** fades ***  2016-07-20 15:34:17,419  fades.helpers      INFO     There is a new version of requests: 2.10.0 and will use it.
*** fades ***  2016-07-20 15:34:17,419  fades.helpers      DEBUG    Getting interpreter version for: None
*** fades ***  2016-07-20 15:34:17,419  fades.helpers      DEBUG    Current interpreter is /home/user3.5
*** fades ***  2016-07-20 15:34:17,419  fades.cache        DEBUG    Searching a venv for reqs: {'pypi': [Requirement.parse('ipython==5.0.0'), Requirement.parse('requests==2.10.0')]} and interpreter: /home/user3.5
*** fades ***  2016-07-20 15:34:17,419  fades.cache        DEBUG    No matching venv found :(
*** fades ***  2016-07-20 15:34:17,420  fades.envbuilder   DEBUG    Env will be created at: /home/user/.local/share/fades/a789c60b-2e95-46ab-b34f-787392112e11
> …/Vcs/fades/fades/envbuilder.py(60)__init__()
-> if sys.version_info >= (3, 4):
(Pdb) c
*** fades ***  2016-07-20 15:34:20,483  fades.envbuilder   DEBUG    Creating virtualenv with pyvenv. options=[]
*** fades ***  2016-07-20 15:34:21,137  fades.envbuilder   DEBUG    env_bin_path: /home/user/.local/share/fades/a789c60b-2e95-46ab-b34f-787392112e11/bin
*** fades ***  2016-07-20 15:34:21,137  fades.envbuilder   DEBUG    pip isn't installed in the venv, setting pip_installed=False
*** fades ***  2016-07-20 15:34:21,138  fades.envbuilder   DEBUG    Installing dependencies for repo 'pypi': requested=[Requirement.parse('ipython==5.0.0'), Requirement.parse('requests==2.10.0')]
*** fades ***  2016-07-20 15:34:21,138  fades.pipmanager   INFO     Need to install a dependency with pip, but no builtin, doing it manually (just wait a little, all should go well)
*** fades ***  2016-07-20 15:34:21,138  fades.pipmanager   DEBUG    Using pip installer from '/home/user/.local/share/fades/get-pip.py'
*** fades ***  2016-07-20 15:34:21,138  fades.pipmanager   DEBUG    Installing PIP manually in the virtualenv
*** fades ***  2016-07-20 15:34:21,138  fades.exec         DEBUG    Executing external command: ['/home/user/.local/share/fades/a789c60b-2e95-46ab-b34f-787392112e11/bin/python', '/home/user/.local/share/fades/get-pip.py', '-I']
*** fades ***  2016-07-20 15:35:37,111  fades.exec         DEBUG    :: Collecting pip
*** fades ***  2016-07-20 15:35:37,333  fades.exec         DEBUG    ::   Using cached pip-8.1.2-py2.py3-none-any.whl
*** fades ***  2016-07-20 15:35:37,392  fades.exec         DEBUG    :: Installing collected packages: pip
*** fades ***  2016-07-20 15:35:38,034  fades.exec         DEBUG    :: Successfully installed pip-8.1.2
*** fades ***  2016-07-20 15:35:38,110  fades.pipmanager   INFO     Installing dependency: ipython==5.0.0
*** fades ***  2016-07-20 15:35:38,110  fades.exec         DEBUG    Executing external command: ['/home/user/.local/share/fades/a789c60b-2e95-46ab-b34f-787392112e11/bin/pip', 'install', 'ipython==5.0.0']

(Pdb) os.environ['PATH']
'…/pyenv/tmp-system-omRbBR/bin:/home/user/.pyenv/libexec:/home/user/.pyenv/plugins/python-build/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/bin:/home/user/.lo

*** fades ***  2016-07-20 15:43:17,017  fades.pipmanager   ERROR    Error installing ipython==5.0.0: [Errno 2] No such file or directory: '/home/user/.local/share/fades/a789c60b-2e95-46ab-b34f-787392112e11/bin/pip'
Traceback (most recent call last):
  File "…/Vcs/fades/fades/pipmanager.py", line 62, in install
    helpers.logged_exec(args)
  File "…/Vcs/fades/fades/helpers.py", line 68, in logged_exec
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/fades/a789c60b-2e95-46ab-b34f-787392112e11/bin/pip'
*** fades ***  2016-07-20 15:43:17,017  fades.envbuilder   DEBUG    Installation Step failed, removing virtualenv
```

`pip` gets installed into `…/pyenv/tmp-system-omRbBR/bin`, which is the temporary virtualenv I've created (through pyenv), and which is first in `PATH`.

It looks like `get-pip.py` executes `python` from the `PATH` somehow internally.

I could imagine that prefixing `PATH` with the `bin` dir for the virtualenv to be created might help, but have not investigated yet.

btw: the following line is strange, but might be just another (minor) issue:

> Current interpreter is /home/user3.5

**Comment by facundobatista** [comment]
I'm trying to remember a case where we wanted to make fades to work inside a virtualenv and we couldn't make it, as it depends of stuff in the normal system to create and install stuff in the virtualenv?

We've been exploring the issue for hours until we decided it wasn't possible (or that the cost to make it so was way over the benefits).

Maybe @gilgamezh remember anything about that case? It happened in a PyCamp, IIRC we worked in that case with @jmansilla ?

Now that I write this, I think that we even explored the case of creating a virtualenv (manually), and then *from inside*, tried to create *another* virtualenv, and we started to see the same problems we had when trying to do it with fades?

In any case, 'fades' is more like a "system utility", the recommended way to install it is system wide...

**Comment by blueyed** [comment]
Thanks, I see that is should not be used in a virtualenv, but I've ran into this when trying to debug / look into some other issue I was seeing, and the thought it should be installed in a virtualenv to develop on it.
What is the recommended way to develop fades then?

I am at the EP btw (also for the sprints), and would be happy to look into this more in-depth.

What do you think about massaging `PATH` and/or look into what `get-pip.py` is doing/calling?
After all, I also wonder if it's something that does not work as expected with `pyenv` and `ensurepip`?!
Maybe instead of calling `get-pip.py`, `python -m pip` should be used?!

**Comment by facundobatista** [comment]
Hello!

I'll be on Saturday in the sprints most of the day, so let's talk any issue or doubt you have!

Regarding last comments, two separated things:

- best way to develop "fades" itself is just to clone the project from github and start playing with it :); you can execute it directly doing "bin/fades", *from the project*, or run the tests doing "./test" (which will install some dependencies using fades itself from the very project, so you would not need to care about that).

- regarding not executing `get-pip.py`, we create the virtualenv in the best generic way we can from inside Python (if you don't specify a different python), or just different external ways. Virtualenv should install pip already in those cases, and we would never need to install pip manually, but note that this still is needed in some platforms because the way python and virtualenv are packaged (most notable, some latests Ubuntus). In any case, we *may* have a bug, so if you have a specific case, let us know exactly which operating system you have, Python versions, what exactly you're doing, etc (simplest way to do this is to run fades with "-v" and paste us that).

Thanks for your time!!

**Comment by facundobatista** [comment]
So, as we talked, I proposed #227 !!

I'm closing this one now.

Thanks for all the help!!
