### ISSUE TITLE
Assure pip install fades works in Windows

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#223]
The problem is that we're specifying a script in the setup.py, and I'm not sure that Windows will really know how to execute that script

**Comment by dragon788** [comment]
You can test this using the AppVeyor (the Windows alternative to TravisCI) platform. I was just coming to suggest adding an AppVeyor build for building and running the code and tests under Windows and saw this issue which would be a good first step in that direction.

**Comment by facundobatista** [comment]
Looks nice, thanks @dragon788 !!

What do you think, @gilgamezh ?

**Comment by facundobatista** [comment]
I just tried this IRL... Win 7, Python 3.6, opened a terminal, did `pip install fades`, downloaded and installed fades 6 correctly.

Then, if I do `python -m fades ...` it works perfectly.

But I can not do `fades`, use it as a script... there's the script set up in the Python's script dir, which is even in the path, and it even has a shebang pointing to the Python executable, but the system does not execute it.

If I rename the script to `fades.py` it IS executed, but fails trying to do `from fades import main` :(

**Comment by facundobatista** [comment]
We need to leave a file called `fades.cmd` in that directory, with the following content: `python -m fades %*`

**Comment by facundobatista** [comment]
fades 7 works perfectly now! just do `pip install fades` and it's left as a system tool from now on
