### ISSUE TITLE
Run modules with -m?

### ISSUE THREAD

**Issue by illume** [PyAr/fades#237]
Hello,

This would be useful to be able to python modules.

Python allows running things as modules with the commands:
```
python -m pygame.examples.aliens
```

Using fades could be done like this:
```
fades --dependency pygame -m pygame.examples.aliens
```

Could it guess the dependency package name as well? I guess that would just be nice to have :)

**Comment by facundobatista** [comment]
So, the idea is that when you do `fades --dependency pygame -m pygame.examples.aliens` it should run, in a virtualenv with only pygame installed, `python -m pygame.examples.aliens`?

I like it! And `-m` is free to use right now. Probably we should add also a `--module`, for consistency.

OTOH, -1 to guessing dependencies, we don't do that in any of other *fades* corner

**Comment by gilgamezh** [comment]
currently, as a workaround you can run `fades -d pygame -x python -m pygame.examples.aliens`
