### ISSUE TITLE
Log format more compact

### ISSUE THREAD

**Issue by juancarlospaco** [PyAr/fades#267]
Fades Log lines starts with `"  *** fades ***  "`.
That Decoration adds no info, but tons of horizontal scrolling.
Can it just *Keep It Simple* as `"fades "`.

Sometimes you find yourself scrolling horizontally just to read:
`IO Error`
`File not Found`
`  *** fades ***   `

Ok with date, time, etc etc, the rest that actually adds information.

Maybe if it needs to be very distinctive to any other output, you can use some UTF-8 character,
since on Python 3 everything defaults to `UTF-8` now, even on Windows:
https://docs.python.org/3.6/whatsnew/3.6.html#pep-529-change-windows-filesystem-encoding-to-utf-8
https://docs.python.org/3.6/whatsnew/3.6.html#pep-528-change-windows-console-encoding-to-utf-8
(eg. Yarn, a JavaScript package manager prints Emoji by default on its log lines to terminal).

Extra points if it can be configured with a config file in your home folder for all executions.

:smile_cat:

**Comment by facundobatista** [comment]
I think we could add a configuring option, like `--log-prefix` to change that. 

After that, you could set it in your `~/.fades` or similar.

**Comment by juancarlospaco** [comment]
Pass the whole line?, like `--log-format` can be even more flexible, 
considering end-users are coders anyway... :thinking:

**Comment by facundobatista** [comment]
What do you mean with --log-format?

Currently, the string "*** fades ***  " is hardcoded, I was thinking about making that configurable, which would fix your issue here.

What else do you have in mind?

**Comment by gilgamezh** [comment]
Incomplete issue. Pleace reopen if you have updates
