### ISSUE TITLE
Fades installs the same dependency multiple times?

### ISSUE THREAD

**Issue by diamond-lizard** [PyAr/fades#279]
In my application, I have:

```python
from prompt_toolkit import prompt
from prompt_toolkit.history import FileHistory
from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
from prompt_toolkit.contrib.completers import WordCompleter
```

If I put `# fades` at the end of each of those lines, fades will tell me:

```
*** fades ***  2017-10-10 00:32:35,603  INFO     Hi! This is fades 6.0, automatically managing your dependencies                                                             
*** fades ***  2017-10-10 00:32:35,610  INFO     Installing dependency: 'prompt-toolkit'                                                                                     
*** fades ***  2017-10-10 00:32:50,852  INFO     Installing dependency: 'prompt-toolkit'                                                                                     
*** fades ***  2017-10-10 00:32:58,400  INFO     Installing dependency: 'prompt-toolkit'                                                                                     
*** fades ***  2017-10-10 00:33:06,013  INFO     Installing dependency: 'prompt-toolkit'
```

Is it really installing the same prompt-toolkit module 4 times?  Shouldn't one time be enough?

Also, it's not clear from the documentation if `# fades` is necessary on each such module import line, or only necessary on the first one (if there are multiple imports from the same module, as in my case).

**Comment by facundobatista** [comment]
Hello!

It's not needed to flag on each import. You can flag just once for `fades` to install that dependency and it will be ok.

That said, if you're flagging several imports and it's installed several times, it's a bug! (that you can easily workaround flagging once per dependency).

Will check, thanks for your time!

**Comment by facundobatista** [comment]
Indeed! We have a bug where if you specify a dependency several times, it's installed several times!

This can be easily tried doing `fades -d DEP -d DEP` where of course both DEPs are the same.

We need to set() the dependencies at some point so there's no duplication.

Thanks for your help telling us about this bug!!

**Comment by gilgamezh** [comment]
I think we should only check duplicated dependencies by repo

if a user is trying to install requests from PyPI and from other source. We won't know what to do.
