### ISSUE TITLE
logging setup should explicitly check if `/dev/log` exists

### ISSUE THREAD

**Issue by vmalloc** [PyAr/fades#282]
Currently on macOS the check at https://github.com/PyAr/fades/blob/master/fades/logger.py#L54 passes, since the handler initialization does not check if `/dev/log` exists. Later when you actually run, the console is spammed heavily with errors:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/handlers.py", line 939, in emit
    self._connect_unixsocket(self.address)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/handlers.py", line 868, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/Cellar/fades/6.0.1_2/libexec/bin/fades", line 33, in <module>
    main.go(sys.argv)
  File "/usr/local/Cellar/fades/6.0.1_2/libexec/lib/python3.6/site-packages/fades/main.py", line 257, in go
    options, pip_options)
  File "/usr/local/Cellar/fades/6.0.1_2/libexec/lib/python3.6/site-packages/fades/envbuilder.py", line 148, in create_venv
    destroy_venv(env_path)
  File "/usr/local/Cellar/fades/6.0.1_2/libexec/lib/python3.6/site-packages/fades/envbuilder.py", line 171, in destroy_venv
    logger.debug("Destroying virtualenv at: %s", env_path)
Message: 'Destroying virtualenv at: %s'
```
A possible solution IMO is to just check existence of `/dev/log` and avoid pushing the syslog handler if it does not exist.

**Comment by vmalloc** [comment]
Just to demonstrate my claim, on macOS:
```

In [1]: import logging.handlers

In [2]: import os

In [3]: os.path.exists('/dev/log')
Out[3]: False

In [4]: logging.handlers.SysLogHandler(address='/dev/log')
Out[4]: <SysLogHandler (NOTSET)>
```

**Comment by facundobatista** [comment]
Thanks for the report! Checking if os.path.exists() looks good... OTOH, I wonder if that 'NOTSET' when showing the handler could be useful...

I mean, could we ask if the handler was properly set? (which would include that /dev/log is there, plus other unknown stuff...

**Comment by vmalloc** [comment]
@facundobatista I doubt there's an API to check if the handler can emit logs, and in half of the cases it swallows exceptions anyways. I think this approach is a good best-effort compromise.

**Comment by gilgamezh** [comment]
@vmalloc I was checking the docs and we can use `/var/run/syslog` in OS/X

https://docs.python.org/3/library/logging.handlers.html#sysloghandler

```
 For example, on Linux it’s usually ‘/dev/log’ but on OS/X it’s ‘/var/run/syslog’. You’ll need to check your platform and use the appropriate address (you may need to do this check at runtime if your application needs to run on several platforms). On Windows, you pretty much have to use the UDP option.
```

Maybe we can check if fades is running in OS/X and change it?

**Comment by vmalloc** [comment]
@gilgamezh Sure, that would be possible to add. Personally I am not sure logging DEBUG to syslog by default is a good thing or an expected behavior (I'm not aware of any other tool that takes the same approach), so I'm good with just silencing syslog on Mac.

If there is an actual demand to bring it back I can craft another PR, but I personally think syslog logging is something users need to opt in to, not out of. Especially when this means losing console logs...

**Comment by facundobatista** [comment]
What about using the path we found? if `/dev/log` is there, use it; else if `/var/run/syslog` is there, use it; else don't log to syslog.

In any case, this would not mean at all to lose console logs...

**Comment by vmalloc** [comment]
@facundobatista ok. I updated the PR based on this suggestion. I see this is tagged for "release 7". Is that happening soon? Currently the UX of fades on macOS is a bit sub-optimal...

**Comment by gilgamezh** [comment]
@vmalloc FYI: we are going to release ASAP. We are closing some issues. You should expect the release in the next days. 

thanks !

**Comment by vmalloc** [comment]
Thanks! Much appreciated.
