### ISSUE TITLE
fades <something> fails with exception instead of handling file not found

### ISSUE THREAD

**Issue by nessita** [PyAr/fades#302]
nessita@miro:~$ sudo apt install fades
[sudo] password for nessita: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  fades
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 20.7 kB of archives.
After this operation, 95.2 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/universe amd64 fades all 5-1 [20.7 kB]
Fetched 20.7 kB in 0s (31.4 kB/s)
Selecting previously unselected package fades.
(Reading database ... 383434 files and directories currently installed.)
Preparing to unpack .../apt/archives/fades_5-1_all.deb ...
Unpacking fades (5-1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up fades (5-1) ...

nessita@miro:~$ fades rst2html5
Traceback (most recent call last):
  File "/usr/bin/fades", line 33, in <module>
    main.go(sys.argv)
  File "/usr/lib/python3/dist-packages/fades/main.py", line 165, in go
    indicated_deps = parsing.parse_srcfile(args.child_program)
  File "/usr/lib/python3/dist-packages/fades/parsing.py", line 194, in parse_srcfile
    with open(filepath, 'rt', encoding='utf8') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'rst2html5'

**Comment by facundobatista** [comment]
We need to improve the message when the user passes a script that doesn't exist (maybe even suggesting to use -x if what wants to be executed would be inside the venv)

**Comment by facundobatista** [comment]
All done!
