### ISSUE TITLE
Bug on AppVeyor

### ISSUE THREAD

**Issue by juancarlospaco** [PyAr/fades#309]
Reproducible bug on AppVeyor only:

- https://ci.appveyor.com/project/facundobatista/fades/build/1.0.125/job/vsgiqqlnro3g1nue#L273
- https://ci.appveyor.com/project/facundobatista/fades/build/1.0.120/job/64po6l1r8bporxhm#L270
- https://ci.appveyor.com/project/facundobatista/fades/build/1.0.125/job/vsgiqqlnro3g1nue#L273
:bug:

**Comment by facundobatista** [comment]
This PR #313 should fix it

**Comment by gilgamezh** [comment]
merged!

**Comment by juancarlospaco** [comment]
A Hueso Me. :grinning::+1:
