### ISSUE TITLE
Better description for github repo

### ISSUE THREAD

**Issue by matagus** [PyAr/fades#319]
How fades repo appears right now in github search results:

<img width="598" alt="screen shot 2018-04-30 at 11 46 49 am" src="https://user-images.githubusercontent.com/58519/39433423-356877d4-4c6c-11e8-9b9a-9e4ea6fe760e.png">

How fades repo appears in my timeline:

<img width="695" alt="screen shot 2018-04-30 at 11 42 54 am" src="https://user-images.githubusercontent.com/58519/39433392-1c985d0a-4c6c-11e8-9e54-d54869cbf839.png">

What's the issue?

The repo description says nothing to users that doesn't know *what fades is*. Also a better description  should make fades repo appear in more searchs.

**Comment by facundobatista** [comment]
Fixed! Thanks for reporting this!
