### ISSUE TITLE
It should accept -r multiple times

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#320]
This way the following could be done: `fades -r reqs.txt -r reqs_devel.txt`

**Comment by andresdelfino** [comment]
Perhaps we should raise an exception when two requirement files mention the same package with different versions?

**Comment by facundobatista** [comment]
We should grab all dependencies and mix them (not override anything).

Most of the difficult questions you ask are also present for the same file anyway (e.g.: what if I include requests==1 and request==2 in the same req.txt file?)

**Comment by gilgamezh** [comment]
```
(test)  /tmp  pip install -r reqs1.txt -r reqs2.txt                                                                                                                 2ms 
Double requirement given: requests==2.18.3 (from -r reqs2.txt (line 1)) (already in requests==2.18.4 (from -r reqs1.txt (line 1)), name='requests')
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test)  ✘  /tmp  pip install -r reqs2.txt -r reqs1.txt                                                                                                           407ms 
Double requirement given: requests==2.18.4 (from -r reqs1.txt (line 1)) (already in requests==2.18.3 (from -r reqs2.txt (line 1)), name='requests')
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test)  ✘  /tmp                                                          
```

**Comment by andresdelfino** [comment]
I think it makes sense to follow pip's handling of these cases.

When there's a decision about this I'll be glad to implement it.

**Comment by facundobatista** [comment]
Let's merge all dependencies and `pip` will decide if they make sense or something is colliding.

So the current PR is going in the good direction. Let's fix some stuff I requested there... Thanks!!!

**Comment by andresdelfino** [comment]
Yes, I agree. If pip is catching whatever conflict that might happen, it's best not to duplicate that logic.

**Comment by facundobatista** [comment]
Already in master! Thanks!!
