### ISSUE TITLE
Export PYTHONPATH

### ISSUE THREAD

**Issue by frafra** [PyAr/fades#329]
fades modifies PATH, but it doesn't change PYTHONPATH.
This would allow external programs to run Python scripts with fades without having to use workarounds.

Example with uwsgi:
```
$ fades -r requirements.txt -x python3 -c "import subprocess, sys; subprocess.run('/usr/sbin/uwsgi --http-socket 0.0.0.0:8000 --plugin python3 --wsgi-file example.py --callable __hug_wsgi__'.split(), env={'PYTHONPATH':':'.join(sys.path)})"
```

Same example having set PYTHONPATH (manually):
```
$ export PYTHONPATH="$HOME/.local/share/fades/15c4ab4e-27b4-49e8-ac4f-7ac20e5ae68d/lib/python3.6/site-packages"
$ fades -r requirements.txt -x /usr/sbin/uwsgi --http-socket 0.0.0.0:8000 --plugin python3 --wsgi-file example.py --callable __hug_wsgi__
```

It would be nice to just use the last command without having to set PYTHONPATH :-)

A flag for PYTHONPATH would make things even easier:

What I use now:
```
$ uwsgi --http-socket 0.0.0.0:8000 --plugin python3 --wsgi-file example.py --callable __hug_wsgi__ --pythonpath $(fades -r requirements.txt -x python -c "import sys;print(sys.path[-1])")
```

What it would be nice to have:
```
$ uwsgi --http-socket 0.0.0.0:8000 --plugin python3 --ws-file example.py --callable __hug_wsgi__ --pythonpath $(fades -r requirements.txt --show-pythonpath)
```

**Comment by facundobatista** [comment]
Hello Francesco! 

I've been thinking about this issue a little the last days, sorry to not answer before.

A priori I don't like about messing with PYTHONPATH, Python paths are tricky under virtualenvs, and `fades` tends to not add any magic over what the virtualenv mechanism itself provides.

That said, let us understand your case better, to see if maybe we could find a workaround or do some coding to support that better. That line with `-x /usr/sbin/uwsgi ` confuses me, the `-x` modifier is to execute stuff from inside the virtualenv, not from outside... that actually works? May you show us an example after running that with `--verbose`? Thanks!

But still trying to understand the use case... reading what you use now... your idea is that `uwsgi` should run `example.py` in the virtualenv created by `fades`? 

This is probably the idea we should focus on.

**Comment by frafra** [comment]
Hi Batista,

thank you for your reply! You are right, it is probably better to take a step back and think about the issue I have at the beginning: how to use uwsgi with fades? :-)

Fiddling around with PYTHONPATH is just a generic trick in order to make it work. I can confirm that exporting PYTHONPATH and using the `-x` modifier works. Here is the output using `--verbose`:

```
$ fades --verbose -r requirements.txt -x /usr/sbin/uwsgi --http-socket 0.0.0.0:8000 --plugin python3 --wsgi-file app.py --callable __hug_wsgi__
*** fades ***  2018-06-27 17:51:33,771  fades              DEBUG    Running Python sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0) on 'Linux-4.16.14-300.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight'
*** fades ***  2018-06-27 17:51:33,771  fades              DEBUG    Starting fades v. 7.0
*** fades ***  2018-06-27 17:51:33,771  fades              DEBUG    Arguments: Namespace(check_updates=False, child_options=['--http-socket', '0.0.0.0:8000', '--plugin', 'python3', '--wsgi-file', 'app.py', '--callable', '__hug_wsgi__'], child_program='/usr/sbin/uwsgi', clean_unused_venvs=None, dependency=None, executable=True, ipython=False, no_precheck_availability=False, pip_options=[], python=None, python_options=[], quiet=False, remove=None, requirement='requirements.txt', system_site_packages=False, verbose=True, version=False, virtualenv_options=[])
*** fades ***  2018-06-27 17:51:33,772  fades.cache        DEBUG    Using cache index: '/home/frafra/.local/share/fades/venvs.idx'
*** fades ***  2018-06-27 17:51:33,773  fades              DEBUG    Dependencies from requirements file: {'pypi': [Requirement.parse('hug')]}
*** fades ***  2018-06-27 17:51:33,773  fades              DEBUG    Dependencies from parameters: {}
*** fades ***  2018-06-27 17:51:33,773  fades.helpers      DEBUG    Getting interpreter version for: None
*** fades ***  2018-06-27 17:51:33,774  fades.helpers      DEBUG    Current interpreter is /usr/bin/python3.6
*** fades ***  2018-06-27 17:51:33,774  fades.cache        DEBUG    Searching a venv for: reqs={'pypi': {Requirement.parse('hug')}} interpreter=/usr/bin/python3.6 options={'pyvenv_options': [], 'virtualenv_options': []}
*** fades ***  2018-06-27 17:51:33,774  fades.cache        DEBUG    Found a matching venv! {'timestamp': 1527451877, 'installed': {'pypi': {'hug': '2.4.0'}}, 'metadata': {'env_path': '/home/frafra/.local/share/fades/15c4ab4e-27b4-49e8-ac4f-7ac20e5ae68d', 'env_bin_path': '/home/frafra/.local/share/fades/15c4ab4e-27b4-49e8-ac4f-7ac20e5ae68d/bin', 'pip_installed': True}, 'interpreter': '/usr/bin/python3.6', 'options': {'pyvenv_options': [], 'virtualenv_options': []}}
*** fades ***  2018-06-27 17:51:33,774  fades              DEBUG    Calling child program '/usr/sbin/uwsgi' with options ['--http-socket', '0.0.0.0:8000', '--plugin', 'python3', '--wsgi-file', 'app.py', '--callable', '__hug_wsgi__']
*** Starting uWSGI 2.0.16 (64bit) on [Wed Jun 27 17:51:33 2018] ***
[...]
```

**Comment by facundobatista** [comment]
Hi Francesco!

We've been talking with @gilgamezh about this, and defined a course of action: fades will have a --get-site-packages` option (see #330) that will just return the venv site-packages dir, so you would be able to do the following:

```
PYTHONPATH=`fades -r requirements.txt --get-site-packages` /usr/sbin/uwsgi --http-socket 0.0.0.0:8000 --plugin python3 --wsgi-file example.py --callable __hug_wsgi__
```

Please tell us that this is enough for your case and that would work fine...

As part of this analysis, we also determined that executing processes external to the virtualenv shouldn't be possible from fades (see #331).

All that said, we have a question. Why don't you just install uWSGI as part of the virtualenv dependencies and execute it from there?

Thanks for your time and all the help!!!

**Comment by frafra** [comment]
Hi :)
That would be a nice improvement in my opinion.

In my specific case uWSGI cannot be installed from pip due to a glibc bug on some Linux distributions and the master branch do not compile correctly. pip is great when you need Python-only libraries, but it can give unexpected/inconsistent results when compiling based on the operating system you are using. 

Thank you all for your very nice comments :)

**Comment by gilgamezh** [comment]
@frafra Yes it will stick to the standard behavior. It will find or create for a venv and then show you the path instead of executing a child. 

grazie mille!

**Comment by facundobatista** [comment]
So, do we all agree to close this issue, leaving #330 as the one that describe the solution to the problem? Thanks!!

**Comment by frafra** [comment]
I agree! Thank you :)
