### ISSUE TITLE
Add --auto mode to catch or predict missing imports

### ISSUE THREAD

**Issue by techtonik** [PyAr/fades#348]
It would greatly save the time if `fades` provided `--auto` mode that could predict missing imports without explicit markup (like `golang`). Maybe it could handle ImportError exceptions, guess the best dependency, install it and continue script execution.

```
$ cat xxx.py 
import requests

print(requests.get("https://google.com"))

$ fades xxx.py
Traceback (most recent call last):
  File "xxx.py", line 1, in <module>
    import requests
ImportError: No module named 'requests'
```

I don't know if it is possible to provide generic ImportError handler, but it should be possible to do this with [revdb](https://bitbucket.org/pypy/revdb/).

**Comment by gilgamezh** [comment]
I think we prefer to be explicit indicating the  dependencies. It would be a "magic" feature and as you know "Explicit is better than implicit"

@facundobatista WDYT?

**Comment by facundobatista** [comment]
Hola @techtonik !

Guessing a dependency is a path we do not want to take (specially not only because it's very error prone, but potentially dangerous, as not all packages from PyPI are "safe"), so we do NOT want to install something unless you specified it.

Thanks for the idea, though! It's always nice hearing from you.

**Comment by techtonik** [comment]
I don't mind adding explicit comments like `pypi:packagename`or `https://pypi.org/project/astdump` if `fades` could parse it. I don't like adding explicit dependency on `fades`.

**Comment by facundobatista** [comment]
Let me see if I understand correctly...

You're ok with doing...

```
import requests  # pypi:requests
```

...but against doing....

```
import requests  # fades
```
....?

**Comment by techtonik** [comment]
Right.

**Comment by facundobatista** [comment]
Better explicit than implicit.

If the import line will be parsed and used by fades, the comment should start with `fades`, and not with different combinations that may be used by fades and be surprising.
