### ISSUE TITLE
Way to install current package

### ISSUE THREAD

**Issue by lukka5** [PyAr/fades#349]
If I get / download a Python package I would like to run the tests to ensure test are passing. I would like to install the package, it's dependencies and then running the test suite. Something like:

    fades -r requirements.txt -d . -x pytest  # Assuming pytest is in requirements.txt

But requirements `.` is not supported by parsing. Alternatively something like this:

    fades -d .[test] -x pytest  # Assuming pytest is in setup.py extra_require

Is someway to achieve this? Not sure if it's related to https://github.com/PyAr/fades/issues/222

**Comment by gilgamezh** [comment]
hello! we support install from a path. So you can run something like `fades -d file://$(pwd)`

**Comment by facundobatista** [comment]
Hello lukka5!

I'm not fully understanding the case... You download a Python package from somewhere, unpack it in your disk, and then want to use fades to run its tests? Or you use fades to install a package inside a virtualenv, and then want to run the tests for that package? Or a third thing?

Thanks!

**Comment by facundobatista** [comment]
Bumping this, it's been a year without response from the OP.

**Comment by lukka5** [comment]
So sorry, I completely overlooked this. @gilgamezh answer works perfectly. I needed to do something like this:
```
git clone <repo>
cd <repo>
fades -r requirements.txt -d file://$(pwd) -x pytest
```
Thanks for this amazing utility.
