### ISSUE TITLE
Ignore commented lines

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/fades#38]
Fades is correctly logging a warning but I think that it has to be ignored.

```
*** fades ***  2015-02-23 11:21:08,688  fades.parsing      WARNING  Not understood import info: ['#from', 'bs4', 'import', 'BeautifulSoup']
```

**Comment by facundobatista** [comment]
I'd set this one to "Release 3". Why? It's not a critical change (stuff works the same), and we have enough stuff in "Release 2" (so I'll defer everything no critical to the future).

Your call, though, change it if agree, leave it for R2 if you don't :)

**Comment by gilgamezh** [comment]
I agree :+1:
