### ISSUE TITLE
Update travis for modern Pythons

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#386]

**Comment by gilgamezh** [comment]
related: 

https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com

**Comment by gilgamezh** [comment]
there is a beta to migrate: 

![image](https://user-images.githubusercontent.com/1496486/78472905-c11f0480-773c-11ea-84ac-e092dc5549be.png)
