### ISSUE TITLE
Suggestion: Use -U as short option for --check-updates

### ISSUE THREAD

**Issue by smheidrich** [PyAr/fades#418]
It would be cool if `-U` was the short option for `--check-updates`, just like it's short for `--upgrade` in `pip install`. Makes it easier to remember.

I was pleasantly surprised that `-p` is the short option for specifying the Python interpreter (matching `-p` in `virtualenv`), so this would be another one of those :)

**Comment by facundobatista** [comment]
It's a good idea!

**Comment by facundobatista** [comment]
Fixed in #422
