### ISSUE TITLE
Anyway to catch KeyboardInterrupt ?

### ISSUE THREAD

**Issue by gabrielo77** [PyAr/fades#55]
Hi,

I tried to catch keyboardInterrupt from my script but fades keep raising the exception, is there anyway to catch it or avoid seeing fades stack trace ? Of course  i can redirect stderr, but maybe i'm missing the way to do it within python.

Thank you for fades, it's being really helpful!

**Comment by facundobatista** [comment]
Let me see if I understand correctly what are you doing....

You start your script with fades, and *while fades is working* you do ctrl-c, and fades fails to stop?

Or you ctrl-c after fades gave control to your script?

Thanks!

**Comment by gabrielo77** [comment]
After fades gave control to my script I do ctrl-c and fades prints its
trace, something like:

^CTraceback (most recent call last):
  File "/usr/bin/fades", line 45, in <module>
    main.go(version, sys.argv)
  File "/usr/share/fades/fades/main.py", line 123, in go
    rc = subprocess.call([python_exe, child_program] + child_options)
  File "/usr/lib/python3.4/subprocess.py", line 539, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.4/subprocess.py", line 1565, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.4/subprocess.py", line 1513, in _try_wait
    (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
  File "/usr/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

On 5 March 2015 at 12:23, Facundo Batista <notifications@github.com> wrote:

> Let me see if I understand correctly what are you doing....
>
> You start your script with fades, and *while fades is working* you do
> ctrl-c, and fades fails to stop?
>
> Or you ctrl-c after fades gave control to your script?
>
> Thanks!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/fades/issues/55#issuecomment-77382745>.
>



-- 
Gabriel.

**Comment by facundobatista** [comment]
I understand now. The signal from the OS comes to the parent process.

Will investigate what we can do about this.

**Comment by gabrielo77** [comment]
I can make a PR that I think solves this

On 5 March 2015 at 13:25, Facundo Batista <notifications@github.com> wrote:

> I understand now. The signal from the OS comes to the parent process.
>
> Will investigate what we can do about this.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/fades/issues/55#issuecomment-77395759>.
>



-- 
Gabriel.

**Comment by facundobatista** [comment]
Uh, sorry, I already fixed it.

Thanks for your time!
