### ISSUE TITLE
Support different Python versions for child execution

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#6]
This will be automatically decided by fades being executed like 'fades' or 'fades3', or 'fades2.7', etc...

**Comment by gilgamezh** [comment]
@facundobatista I need some help here. 

First of all I think that this branch needs a merciless code review ;) 
https://github.com/PyAr/fades/compare/different_interpreter_versions

Then:
- How can I 'upgrade' de venvs database?
- How can I test create a venv with virtualenv?

**Comment by facundobatista** [comment]
In fades/envbuilder.py:

- create_with_virtualenv has no docstrings

- don't do this:

    args = args[:3] + ['--no-pip'] + args[3:]

  (use args.insert)

- the try/except you created is too big, you're wrapping too many different lines inside; do a try/except ImportError for the import, and then a try/except fr the command execution (not the args building, etc)

- why this and not executing 'virtualven' directly?

    virtualenv_exe = sys.executable.replace('python', 'virtualenv')


In fades/helpers.py:

- don't do this:

    "{}/{}".format(path, file))

  (use os.path.join)

- 'which' function has no docstring

- 'get_interpreter_version' has a docstring with first line not a single line.

- don't do:

        if not '/' in requested_version:

  do:

        if '/' not in requested_version:

- I don't understand this:

    if not any([char.isdigit() for char in requested_version]):

  because that code is important if user passed "python" or "python2", no matter the number


In general:

- you're considering the file name for the 'interpreter', like in the following line:

    interpreter = sys.executable.split('/')[-1]

  this breaks in the situation when /usr/bin/python and /usr/local/bin/python and /home/development/python are different...

- tests failed:

    http://linkode.org/5Rh9fz5Xe2XQ4QgtVLyEQ1

**Comment by gilgamezh** [comment]
Test are failing I'm working in it. I think that we can release this week. :smile:
