### ISSUE TITLE
Support branching/installing directly from repositories

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#7]
This is:
 - github
 - launchpad
 - bitbucket

We need a way to mark (in the import) not only the repository, but also the protocol used (e.g., bitbucket can work with hg or git)

**Comment by juancarlospaco** [comment]
`pip install git+https://github.com/user/example.git` **==** `import example  # fades git+https://github.com/user/example.git` :grey_question: 
:smile_cat:

**Comment by facundobatista** [comment]
That's the idea, or at least most of it, yes

**Comment by juancarlospaco** [comment]
:smile_cat::+1:
