### ISSUE TITLE
Importar automagicamente las dependencias en el modo interactivo

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/fades#70]
Cuando un usuario hace:

fades -d requests

Abrir el interprete python requests ya importado. :question: :

**Comment by facundobatista** [comment]
Mmm... what would happen if importing the module has a side effect?

Maybe we could add another option, like "-i", which means "a venv with this module, but also this module imported."

**Comment by gilgamezh** [comment]
or with a upper d "-D" ?

**Comment by facundobatista** [comment]
Is it actually possible to start a python interactive interpreter with a module pre-imported?

**Comment by gilgamezh** [comment]
I have to check how django shell_plus does it. ;) 

On 19 June 2015 09:47:35 GMT-03:00, Facundo Batista <notifications@github.com> wrote:
>Is it actually possible to start a python interactive interpreter with
>a module pre-imported?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PyAr/fades/issues/70#issuecomment-113505191

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gilgamezh** [comment]
use `python -i -c "import time"`

**Comment by facundobatista** [comment]
Actually, I would prefer to make this the default behaviour.

If you're starting the interpreter in a venv with some dependencies, most probably you will use those dependencies.

This happens to me 100% of the time.

So, when opening an interpreter, actually import the dependencies. Extra points for:
- try/except, for the case of not guessing what to import!
- tell the user what happened (both when imported ok or not)

Of course, we would need to add a parameter `--disable-autoimport` to NOT import everything automatically.

What do you think?

**Comment by gilgamezh** [comment]
agree it should be the default. +1

**Comment by facundobatista** [comment]
Created #389  for this.
