### ISSUE TITLE
Enable the use of fade's arguments in Shebang line

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/fades#82]
```
  1 #!/usr/bin/env fades -r /tmp/reqs.txt -p python2                                                    
  2 print("hola mundo") 
```

**Comment by facundobatista** [comment]
I don't get to understand this issue...

**Comment by gilgamezh** [comment]
I was exited and I wasn't clear :p 

The Idea is to enable the use of arguments in the shebang line.

Example

```
#!/usr/bin/env fades -r /path/to/requirements.txt --python=python3.3
```

I remember that you was testing it at the bsas pyar meetup.

With this `fades` will be able to be used for any python project!  :smile:

**Comment by facundobatista** [comment]
This already works :D

**Comment by gilgamezh** [comment]
here the commit: https://github.com/PyAr/fades/commit/349c9d8ee11e0c8b515e95ccf215b76c3a1dd34b
