### ISSUE TITLE
Support a config file

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#87]
By default, a ".fades" in the executing dir.

If nothing in the executing dir, check a .fades in $HOME.

Or, a user could indicate one with --config or something

**Comment by facundobatista** [comment]
Convention: the key in the file is the same name as the parameter, without the initial "--", and changing "-" to "_" ...

**Comment by facundobatista** [comment]
Support config file in "/etc/fades.ini", "$HOME/.fades.ini", "$HOME/.config/fades.ini", "./.fades.ini", merging all the parameters (or adding, if the parameter is "multiple")

**Comment by gilgamezh** [comment]
I'm not sure about 

> (or adding, if the parameter is "multiple")

I think that the file with the highest prioroty have to override the others. So you can have different options for a project.

priority == `"/etc/fades.ini", "$HOME/.fades.ini", "$HOME/.config/fades.ini", "./.fades.ini" -> argparse`

what do you think?

**Comment by facundobatista** [comment]
Making it to use only the highest priority file will spoil the solution of having some config in one place and some config in other.

For example, you put an option for the "pip cache" in /etc/fades.ini and it will work for all the projects, unless you have a config file in the project, which will avoid using the global one.

Do you really think there will be a need for a project to "not use" the global configuration? 

Most options are "simple", in the sense that if you put them in the project's config will override previous configs. The only options that are "multiple" are:

- dependency
- virtualenv-options
- pip-options

If you think there will be a need like "make the projects config to ignore the global pip options" (or similar for the other parameters), we could have some syntax for the config file lile "--pip-options=RESET" which will make discard all the previous options for that parameter... I'm -0 to include something like this right now unless you're very sure that will be needed...
