### ISSUE TITLE
Make symlinks from system to the venv

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#91]
Can do, for example:

```
from PyQt5 import core  # fades::system
```

And fades will not install that dependency in the venv, but symlink it from the external system.

The path from where to symlink could be found out importing the module itself.

**Comment by ralsina** [comment]
Probably you can do that without importing using "something" in [importlib](https://docs.python.org/3/library/importlib.html)

**Comment by facundobatista** [comment]
Probably, yes.

And if the venv is for not-the-current-python, we can do something like:

    'python2 -c "import os.path as _, {0}; print _.dirname(_.realpath({0}.__file__[:-1]))"'.format(module_name)

**Comment by gilgamezh** [comment]
It can be solved using `--system-site-packages` and we can still live in the "standard" world (implementing this feature is a kind of hack)
