### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by humitos** [PyAr/fades#92]
Hi people,

Sincerely, I think you chose a really bad name for the project... Or "command" actually. It's very complicated to type `fades` every time you want to execute a Python script because it's typed with just one hand and you need to use same finger for `d` and for `e`, so it's tricky (at least in Spanish / English keyboard layout).

This issue report is half joke and half a reality on the daily uses...

So, as developers that we like to type fast, we should think about these things...

Cheers, ;)

**Comment by facundobatista** [comment]
Hola!

On one hand, remember that you can put fades on top of your script:  #!/usr/bin/fades  and you'll never need to type it again.

On the other hand, you can do  alias whateveryouwant=fades

Salud :)

**Comment by gilgamezh** [comment]
LOL
